import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// shared settings to keep this clean
const common = {
	banner: { js: banner },
	bundle: true,
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
};

async function start() {
	// context for js
	const jsContext = await esbuild.context({
		...common,
		entryPoints: ['main.ts'],
		outfile: 'main.js',
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/view',
			...builtins,
		],
	});

	// context for css
	const cssContext = await esbuild.context({
		...common,
		entryPoints: ['lib/styles/index.css'],
		outfile: 'styles.css',
	});

	if (prod) {
		// build once and exit
		await jsContext.rebuild();
		await cssContext.rebuild();
		process.exit(0);
	} else {
		// watch both continuously
		await jsContext.watch();
		await cssContext.watch();
	}
}

start();
